production:
  adapter: mysql2
  database: mgis_prod
  host: <%= ENV['MGIS_DATABASE_HOST'] %>
  username: <%= ENV['MGIS_DATABASE_USERNAME'] %>
  password: <%= ENV['MGIS_DATABASE_PASSWORD'] %>
  encoding: utf8
  socket: <%= ENV['MGIS_DATABASE_SOCKET'] %>
development:
  adapter: mysql2
  database: mgis_dev
  host: <%= ENV['MGIS_DATABASE_HOST'] %>
  username: <%= ENV['MGIS_DATABASE_USERNAME'] %>
  password: <%= ENV['MGIS_DATABASE_PASSWORD'] %>
  encoding: utf8
  pool: 25
  socket: <%= ENV['MGIS_DATABASE_SOCKET'] %>

test:
  adapter: mysql2
  database: mgis_test
  host: <%= ENV['MGIS_DATABASE_HOST'] %>
  username: <%= ENV['MGIS_DATABASE_USERNAME'] %>
  password: <%= ENV['MGIS_DATABASE_PASSWORD'] %>
  encoding: utf8
  pool: 25
  socket: <%= ENV['MGIS_DATABASE_SOCKET'] %>